# Stage 1: Build the Angular application
FROM node:alpine as build
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm cache clean --force
RUN npm install --legacy-peer-deps
COPY . .
RUN npx nx build mifiware-tfm --base-href /mifiware-tfm/ --configuration=dev