FROM node:18.13.0
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm cache clean --force
RUN npm install --legacy-peer-deps
COPY . .
RUN npm rebuild bcrypt --build-from-source
RUN npx nx build api --base-href /api/ --configuration=dev
EXPOSE 3001
CMD ["npm", "run", "serve:api"]