version: '3.8'

networks:
  default:

services:
  mysql-db:
    container_name: mysql-db
    image: mysql:5.7
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tfm
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - mysql-volume:/var/lib/mysql:rw
    networks:
      - default

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - mysql-db

  api:
    container_name: api
    depends_on:
      - mysql-db
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 3000:3000
    environment:
      - DB_HOST=$MYSQLDB_HOST
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_PASSWORD
      - DB_DATABASE=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      - ./api:/app
      - /app/node_modules
    networks:
      - default

  nginx:
    image: nginx:latest
    depends_on:
      - api
      - mifiware-tfm
    volumes:
      - mifiware-tfm-dist:/var/www/html/mifiware-tfm
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '3050:80'
    restart: always

  mifiware-tfm:
    container_name: mifiware-tfm
    depends_on:
      - api
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 4200:80
    stdin_open: true
    tty: true
    volumes:
      - ./mifiware-tfm:/app
      - /app/node_modules
      - /app/.next
      - mifiware-tfm-dist:/usr/src/app/dist/apps/mifiware-tfm
    networks:
      - default

volumes:
  mysql-volume:
  mifiware-tfm-dist:
