FROM node:18.13.0 as build
WORKDIR /usr/src/app
COPY package*.json ./
ENV NX_DAEMON=false
RUN npm install --force
COPY . .
RUN npx nx build mifiware-tfm --base-href /mifiware-tfm/ --configuration=dev


